language: elixir
elixir: '1.6.6'
otp_release: '21.0'
sudo: required
build: trusty

env: 
- MIX_ENV=test
  
before_install: 
- sudo apt-get -y install openssl libssl-dev libcurl4-openssl-dev
- sudo apt-get -y install libjpeg-dev
- TF_TYPE="cpu"
- OS="linux"
- TARGET_DIRECTORY="/usr/local"
- curl -L "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-${OS}-x86_64-1.9.0.tar.gz" | sudo tar -C $TARGET_DIRECTORY -xz
- sudo ldconfig 

script:
- mix deps.get 
- mix test
